### ISSUE TITLE
VM doesn't come all the way up unless python-git package is pre-installed

### ISSUE THREAD

**Issue by imaginator** [buddycloud/buddycloud-vm#12]
Not sure how to solve this. 

`vagrant up` results in saltstack getting installed but failing becase it needs `python-git` to be able to use 

```
# use the Buddycloud saltstates as fallback
gitfs_remotes:
  - http://github.com/buddycloud/saltstack.git:
```

**Comment by denisw** [comment]
Vagrant allows you to have multiple provisioners. You could add, for instance, a simple [shell provisioner](https://docs.vagrantup.com/v2/provisioning/shell.html) that installs `python-git` before the Saltstack provisioning step runs. (Provisioners are run in the order you declare them in `Vagrantfile`).

Not the most beautiful solution, but it works.

**Comment by imaginator** [comment]
Oh great to know! Thanks for that hint @denisw.

**Comment by imaginator** [comment]
Fixed with https://github.com/buddycloud/buddycloud-vm/commit/da0bd362e19fb85ab9bb3af4f52f03b29a414cfb
